name: image_hashing
description: Generate various image hashes (AHash, PHash, DHash, WHash)
version: 0.1.0
repository: https://github.com/RequieMa/image_hashing
# documentation: https://pub.dev/documentation/your_package_name # 自动生成
issue_tracker: https://github.com/RequieMa/image_hashing/issues

environment:
  sdk: ^3.7.0

dependencies:
  path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

publish_to: none

topics: # 最多5个标签
  - photos
  - images
  - hash
  - dart
